" Name:         Chan-Eink
" Description:  Template for a eink colorscheme
" Author:       Chanilino <myself@somewhere.org>
" Maintainer:   Chanilino<myself@somewhere.org>
" Website:      https://me.org
" License:      Public domain
" Last Updated: lun 24 ene 2022 09:47:18

" Generated by Colortemplate v2.1.0

set background=light

hi clear
let g:colors_name = 'chan_eink'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')

hi! link Boolean Constant
hi! link Character Constant
hi! link Conditional Statement
hi! link Debug Special
hi! link Define PreProc
hi! link Delimiter Special
hi! link Exception Statement
hi! link Float Constant
hi! link Function Identifier
hi! link Include PreProc
hi! link Keyword Statement
hi! link Label Statement
hi! link Macro PreProc
hi! link Number Constant
hi! link Operator Statement
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link SpecialChar Special
hi! link SpecialComment Special
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link StorageClass Type
hi! link String Constant
hi! link Structure Type
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#000000', '#404040', '#707070', '#787878', '#878787', '#8f8f8f', '#afafaf', '#ffffff', '#000000', '#787878', '#9f9f9f', '#ffffff', '#d2d2d2', '#ff6400', '#64ff00', '#ffff64']
  if get(g:, 'chan_eink_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#000000 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
    hi Terminal guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  endif
  hi colorcolumn guifg=fg guibg=#ffffff gui=NONE cterm=NONE
  hi conceal guifg=NONE guibg=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi cursor guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi cursorcolumn guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi cursorline guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi cursorlinenr guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi diffadd guifg=#000000 guibg=#ffffff gui=reverse cterm=reverse
  hi diffchange guifg=#000000 guibg=#ffffff gui=reverse cterm=reverse
  hi diffdelete guifg=#000000 guibg=#ffffff gui=reverse cterm=reverse
  hi difftext guifg=#000000 guibg=#ffffff gui=bold,reverse cterm=bold,reverse
  hi directory guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi endofbuffer guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi errormsg guifg=#000000 guibg=#ffffff gui=bold,reverse cterm=bold,reverse
  hi foldcolumn guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi folded guifg=#000000 guibg=#ffffff gui=italic cterm=italic
  hi incsearch guifg=#000000 guibg=#afafaf gui=standout cterm=NONE
  hi linenr guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi matchparen guifg=#000000 guibg=#afafaf gui=NONE cterm=NONE
  hi modemsg guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi moremsg guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi nontext guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi pmenu guifg=#000000 guibg=#afafaf gui=NONE cterm=NONE
  hi pmenusbar guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi pmenusel guifg=#000000 guibg=#ffffff gui=bold,reverse cterm=bold,reverse
  hi pmenuthumb guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi question guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi search guifg=#000000 guibg=#707070 gui=NONE cterm=NONE
  hi hlsearch guifg=#000000 guibg=#787878 gui=NONE cterm=NONE
  hi signcolumn guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi specialkey guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi spellbad guifg=#000000 guibg=#ffffff guisp=#787878 gui=NONE cterm=NONE
  hi spellcap guifg=#000000 guibg=#ffffff guisp=#9f9f9f gui=NONE cterm=NONE
  hi spelllocal guifg=#000000 guibg=#ffffff guisp=#606060 gui=NONE cterm=NONE
  hi spellrare guifg=#000000 guibg=#ffffff guisp=#878787 gui=reverse cterm=reverse
  hi statusline guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi statuslinenc guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi tabline guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi tablinefill guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi tablinesel guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi title guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi vertsplit guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi visual guifg=#000000 guibg=#afafaf gui=NONE cterm=NONE
  hi VisualNOS guifg=#000000 guibg=#afafaf gui=NONE cterm=NONE
  hi WarningMsg guifg=#606060 guibg=#ffffff gui=bold,reverse cterm=bold,reverse
  hi WildMenu guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi Comment guifg=#000000 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#000000 guibg=#ffffff gui=NONE cterm=NONE
  hi Identifier guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Type guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#000000 guibg=NONE gui=NONE cterm=NONE
  hi CursorIM guifg=NONE guibg=fg gui=NONE cterm=NONE
  hi ToolbarLine guifg=#878787 guibg=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#ffffff guibg=#000000 gui=bold cterm=bold
  if !s:italics
    hi folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'chan_eink_transp_bg', 0)
    hi Normal ctermfg=16 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=16 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=16 ctermbg=231 cterm=NONE
    hi Terminal ctermfg=16 ctermbg=231 cterm=NONE
  endif
  hi colorcolumn ctermfg=fg ctermbg=231 cterm=NONE
  hi conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi cursor ctermfg=16 ctermbg=231 cterm=NONE
  hi cursorcolumn ctermfg=16 ctermbg=231 cterm=NONE
  hi cursorline ctermfg=16 ctermbg=231 cterm=NONE
  hi cursorlinenr ctermfg=16 ctermbg=231 cterm=NONE
  hi diffadd ctermfg=16 ctermbg=231 cterm=reverse
  hi diffchange ctermfg=16 ctermbg=231 cterm=reverse
  hi diffdelete ctermfg=16 ctermbg=231 cterm=reverse
  hi difftext ctermfg=16 ctermbg=231 cterm=bold,reverse
  hi directory ctermfg=16 ctermbg=231 cterm=NONE
  hi endofbuffer ctermfg=16 ctermbg=231 cterm=NONE
  hi errormsg ctermfg=16 ctermbg=231 cterm=bold,reverse
  hi foldcolumn ctermfg=16 ctermbg=231 cterm=NONE
  hi folded ctermfg=16 ctermbg=231 cterm=italic
  hi incsearch ctermfg=16 ctermbg=145 cterm=NONE
  hi linenr ctermfg=16 ctermbg=231 cterm=NONE
  hi matchparen ctermfg=16 ctermbg=145 cterm=NONE
  hi modemsg ctermfg=16 ctermbg=231 cterm=NONE
  hi moremsg ctermfg=16 ctermbg=231 cterm=NONE
  hi nontext ctermfg=16 ctermbg=231 cterm=NONE
  hi pmenu ctermfg=16 ctermbg=145 cterm=NONE
  hi pmenusbar ctermfg=16 ctermbg=231 cterm=NONE
  hi pmenusel ctermfg=16 ctermbg=231 cterm=bold,reverse
  hi pmenuthumb ctermfg=16 ctermbg=231 cterm=NONE
  hi question ctermfg=16 ctermbg=231 cterm=NONE
  hi search ctermfg=16 ctermbg=242 cterm=NONE
  hi hlsearch ctermfg=16 ctermbg=243 cterm=NONE
  hi signcolumn ctermfg=16 ctermbg=231 cterm=NONE
  hi specialkey ctermfg=16 ctermbg=231 cterm=NONE
  hi spellbad ctermfg=16 ctermbg=231 cterm=NONE
  hi spellcap ctermfg=16 ctermbg=231 cterm=NONE
  hi spelllocal ctermfg=16 ctermbg=231 cterm=NONE
  hi spellrare ctermfg=16 ctermbg=231 cterm=reverse
  hi statusline ctermfg=16 ctermbg=231 cterm=NONE
  hi statuslinenc ctermfg=16 ctermbg=231 cterm=NONE
  hi tabline ctermfg=16 ctermbg=231 cterm=NONE
  hi tablinefill ctermfg=16 ctermbg=231 cterm=NONE
  hi tablinesel ctermfg=16 ctermbg=231 cterm=NONE
  hi title ctermfg=16 ctermbg=231 cterm=NONE
  hi vertsplit ctermfg=16 ctermbg=231 cterm=NONE
  hi visual ctermfg=16 ctermbg=145 cterm=NONE
  hi VisualNOS ctermfg=16 ctermbg=145 cterm=NONE
  hi WarningMsg ctermfg=59 ctermbg=231 cterm=bold,reverse
  hi WildMenu ctermfg=16 ctermbg=231 cterm=NONE
  hi Comment ctermfg=16 ctermbg=NONE cterm=italic
  hi Constant ctermfg=16 ctermbg=NONE cterm=NONE
  hi Error ctermfg=16 ctermbg=231 cterm=NONE
  hi Identifier ctermfg=16 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=16 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=16 ctermbg=NONE cterm=NONE
  hi Special ctermfg=16 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=16 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=16 ctermbg=NONE cterm=NONE
  hi Type ctermfg=16 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=16 ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=102 ctermbg=NONE cterm=NONE
  hi ToolbarButton ctermfg=231 ctermbg=16 cterm=bold
  if !s:italics
    hi folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'chan_eink_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi Terminal ctermfg=Black ctermbg=White cterm=NONE
  endif
  hi colorcolumn ctermfg=fg ctermbg=White cterm=NONE
  hi conceal ctermfg=NONE ctermbg=NONE cterm=NONE
  hi cursor ctermfg=Black ctermbg=White cterm=NONE
  hi cursorcolumn ctermfg=Black ctermbg=White cterm=NONE
  hi cursorline ctermfg=Black ctermbg=White cterm=NONE
  hi cursorlinenr ctermfg=Black ctermbg=White cterm=NONE
  hi diffadd ctermfg=Black ctermbg=White cterm=reverse
  hi diffchange ctermfg=Black ctermbg=White cterm=reverse
  hi diffdelete ctermfg=Black ctermbg=White cterm=reverse
  hi difftext ctermfg=Black ctermbg=White cterm=bold,reverse
  hi directory ctermfg=Black ctermbg=White cterm=NONE
  hi endofbuffer ctermfg=Black ctermbg=White cterm=NONE
  hi errormsg ctermfg=Black ctermbg=White cterm=bold,reverse
  hi foldcolumn ctermfg=Black ctermbg=White cterm=NONE
  hi folded ctermfg=Black ctermbg=White cterm=italic
  hi incsearch ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi linenr ctermfg=Black ctermbg=White cterm=NONE
  hi matchparen ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi modemsg ctermfg=Black ctermbg=White cterm=NONE
  hi moremsg ctermfg=Black ctermbg=White cterm=NONE
  hi nontext ctermfg=Black ctermbg=White cterm=NONE
  hi pmenu ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi pmenusbar ctermfg=Black ctermbg=White cterm=NONE
  hi pmenusel ctermfg=Black ctermbg=White cterm=bold,reverse
  hi pmenuthumb ctermfg=Black ctermbg=White cterm=NONE
  hi question ctermfg=Black ctermbg=White cterm=NONE
  hi search ctermfg=Black ctermbg=Grey cterm=NONE
  hi hlsearch ctermfg=Black ctermbg=Grey cterm=NONE
  hi signcolumn ctermfg=Black ctermbg=White cterm=NONE
  hi specialkey ctermfg=Black ctermbg=White cterm=NONE
  hi spellbad ctermfg=Black ctermbg=White cterm=NONE
  hi spellcap ctermfg=Black ctermbg=White cterm=NONE
  hi spelllocal ctermfg=Black ctermbg=White cterm=NONE
  hi spellrare ctermfg=Black ctermbg=White cterm=reverse
  hi statusline ctermfg=Black ctermbg=White cterm=NONE
  hi statuslinenc ctermfg=Black ctermbg=White cterm=NONE
  hi tabline ctermfg=Black ctermbg=White cterm=NONE
  hi tablinefill ctermfg=Black ctermbg=White cterm=NONE
  hi tablinesel ctermfg=Black ctermbg=White cterm=NONE
  hi title ctermfg=Black ctermbg=White cterm=NONE
  hi vertsplit ctermfg=Black ctermbg=White cterm=NONE
  hi visual ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi VisualNOS ctermfg=Black ctermbg=LightGrey cterm=NONE
  hi WarningMsg ctermfg=Grey ctermbg=White cterm=bold,reverse
  hi WildMenu ctermfg=Black ctermbg=White cterm=NONE
  hi Comment ctermfg=Black ctermbg=NONE cterm=italic
  hi Constant ctermfg=Black ctermbg=NONE cterm=NONE
  hi Error ctermfg=Black ctermbg=White cterm=NONE
  hi Identifier ctermfg=Black ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Black ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Black ctermbg=NONE cterm=NONE
  hi Special ctermfg=Black ctermbg=NONE cterm=NONE
  hi Statement ctermfg=Black ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Black ctermbg=NONE cterm=NONE
  hi Type ctermfg=Black ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=Black ctermbg=NONE cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=fg cterm=NONE
  hi ToolbarLine ctermfg=Grey ctermbg=NONE cterm=NONE
  hi ToolbarButton ctermfg=White ctermbg=Black cterm=bold
  if !s:italics
    hi folded cterm=NONE
    hi Comment cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 0
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi PopupSelected term=reverse
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: black         rgb(  0,   0,   0)        ~         Black
" Color: grey01        rgb( 48,  48,  48)        ~         DarkGrey
" Color: grey02        rgb( 64,  64,  64)        ~         DarkGrey
" Color: grey03        rgb( 80,  80,  80)        ~         DarkGrey
" Color: grey04        rgb( 96,  96,  96)        ~         Grey
" Color: grey05        rgb(112, 112, 112)        ~         Grey
" Color: grey06        rgb(120, 120, 120)        ~         Grey
" Color: grey07        rgb(127, 127, 127)        ~         Grey
" Color: grey08        rgb(135, 135, 135)        ~         Grey
" Color: grey09        rgb(143, 143, 143)        ~         Grey
" Color: grey10        rgb(159, 159, 159)        ~         Grey
" Color: grey11        rgb(175, 175, 175)        ~         LightGrey
" Color: white         rgb(255, 255, 255)        ~         White
" Color: brightblack   rgb(210, 210, 210)        ~         DarkGrey
" Color: brightred     rgb(255, 100,   0)        ~         LightRed
" color: brightgreen   rgb(100, 255,   0)        ~         lightgreen
" color: brightyellow  rgb(255, 255, 100)        ~         lightyellow
" Term colors: black grey02 grey05  grey06 grey08 grey09  grey11 white
" Term colors: black grey06 grey10 white
" Term colors: brightblack brightred brightgreen brightyellow
" vim: et ts=2 sw=2
